// example-svelte-app/src/App.svelte
<script>

  let responseFromBackend = ""
  let offers = [
    { roomNumber: 1, rentalCarId: 10 },
    { roomNumber: 2, rentalCarId: 20 },
  ];

  function bookOffer(offer) {
    confirm(`Do you want to book room: ${offer.roomNumber} and rentalCarId: ${offer.rentalCarId}?`)

    // here comes the backend call
    // assumption: booking was successful
    responseFromBackend = `Booking Successful. Enjoy your Vacation. Your confirmation ID is: 4711.`

  }
</script>

<div id="bookingApp">
  <h1>Hey we're going to Ibiza</h1>

  <table class="center">
    <tr>
      <th> Room Number </th>
      <th> Rental Car ID </th>
      <th> Book </th>
    </tr>
    {#each offers as offer}
    
      <tr >
        <td>
          {offer.roomNumber}
        </td>
        <td>
          {offer.rentalCarId}
        </td>
        <td>
          <button on:click={() => bookOffer(offer)}>Book Now</button>
        </td>

        <tr />
      
      {/each}
   
  </table>

  <div id="response">
    {responseFromBackend}
  </div>


  <!-- <div id="response">
        {{responseFromBackend}}
      </div> -->
</div>

<style>
  #bookingApp {
    text-align: center;
  }

  #response {
    margin-top: 5vh;
  }

  table,
  th,
  td {
    border: 1px solid black;
    border-collapse: collapse;
  }

  table.center {
    margin-left: auto;
    margin-right: auto;
  }
</style>

// example-two-phase-commit-showcase-angular/src/app/app.component.ts
import { HttpClient } from '@angular/common/http';
import { Component } from '@angular/core';

export interface IOffer {
  roomNumber: number,
  rentalCarId: number,
}


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {

  public title = 'example-angular-app';
  public offers: IOffer[] = [{roomNumber: 1, rentalCarId: 10}, {roomNumber: 2, rentalCarId: 20}]
  public showList = false
  public responseFromBackend = ""

  public constructor(private http: HttpClient) {

  }

  public async bookOffer(offer: IOffer): Promise<void> {
    confirm(`Do you want to book room: ${offer.roomNumber} and rentalCarId: ${offer.rentalCarId}?`)

    this.http.get('http://localhost:3036/getISSPosition')
      .subscribe((data: any) => {
        console.log(data)
      })

      // assumption: booking successful
      this.responseFromBackend = `Booking Successful. Enjoy your Vacation. Your confirmation ID is: 4711.`

      // assumption: booking not successful

  }

}

<div id="bookingApp">
  <h1>
    Hey we're going to Ibiza
  </h1>

    <table class="center"> 
      <tr>
        <th>
          Room Number
        </th>
        <th>
          Rental Car ID
        </th>
        <th>
          Book
        </th>
      </tr>
      <tr *ngFor="let offer of offers">
        <td>
          {{offer.roomNumber}}
        </td>
        <td>
          {{offer.rentalCarId}}
        </td>
        <td>
          <button (click)="bookOffer(offer)">Book Now</button>
        </td>
      </tr>
    </table>
    
    <div id="response">
      {{responseFromBackend}}
    </div>
  </div>
